POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "jim",
    "password": "jim"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "jim",
    "password": "jim"
}

###
POST http://localhost:5000/api/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ3Y2QyMWQ4MmQwNTY0NGFlZGY3ZWQiLCJpYXQiOjE2NDg4NzI3Mzd9.MZthbJZwhgHlsx05B5ZX8R4R8OU5LKep0KGTRbA9CJI

{
    "title": "React",
    "description": "React",
    "url": "google.com",
    "status": "TO LEARN"
}

###
GET http://localhost:5000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ3Y2QyMWQ4MmQwNTY0NGFlZGY3ZWQiLCJpYXQiOjE2NDg4NzI3Mzd9.MZthbJZwhgHlsx05B5ZX8R4R8OU5LKep0KGTRbA9CJI

###
PUT http://localhost:5000/api/posts/621d938bc434b236e7535fbf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjQ3Y2QyMWQ4MmQwNTY0NGFlZGY3ZWQiLCJpYXQiOjE2NDg4NzI3Mzd9.MZthbJZwhgHlsx05B5ZX8R4R8OU5LKep0KGTRbA9CJI
Content-Type: application/json

{
    "title": "ReactJS",
    "description": "ReactJS",
    "url": "reactjs.org",
    "status": "TO LEARN"
}

###
DELETE http://localhost:5000/api/posts/621d938bc434b236e7535fbf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjFkOTIxYzljYjA1MzA1ZWM5ZDg0NDEiLCJpYXQiOjE2NDYxMTQ3NjN9.VGyiUEcfZs8DzhwX1ePMBnoSCzyHswnIhVnLcnhjyVE